name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
      #with:
        #submodules: recursive

    - name: Prepare submodules
      run: |
        git rm app/src/main/cpp/adrenotools
        git submodule update --recursive
        git clone --recursive https://github.com/Pipetto-crypto/libadrenotools.git app/src/main/cpp/adrenotools
      
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Uploading an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Winlator APK
        path: ./app/build/outputs/apk/debug/app-debug.apk
        
